### PR TITLE
Issue #5934: Hydrate and validate fast-pysf in shared worktrees (cheap-lane worker)

### LINKED ISSUE #5934: friction: shared readiness environment misses fast-pysf GIL-release API
## Goal / Problem

**Observed behavior**

The full `BASE_REF=origin/main scripts/dev/pr_ready_check.sh` gate on PR #5922 stops during collection because the shared virtual environment imports an older installed `pysocialforce` that lacks `pysocialforce.forces.social_force_gil_releasing_context`. The same mismatch causes `pytest -m base_sensitive --collect-only --quiet` to fail with 21 collection errors in training/tool modules.

This repeats the already-closed friction tracked in #5665 after the threaded SocialForce API landed in #5639 / #4981.

**Expected behavior**

A fresh or shared worktree readiness environment should resolve the checked-out `fast-pysf/pysocialforce` API, or fail before collection with a deterministic repair path that the readiness workflow can execute. The base-sensitive selector should collect successfully in a repository-supported environment.

## Reproduction

```bash
BASE_REF=origin/main scripts/dev/pr_ready_check.sh
uv run python -m pytest -m base_sensitive --collect-only --quiet
uv run python scripts/dev/check_fast_pysf_runtime.py
```

Observed 2026-07-17 on gate worktree for PR #5922:

```text
ImportError: cannot import name 'social_force_gil_releasing_context' from 'pysocialforce.forces'
21/17133 tests collected, 21 errors during collection
```

The checkout contains the symbol at `fast-pysf/pysocialforce/forces.py`; the reused environment resolves `/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.12/site-packages/pysocialforce/forces.py` without it.

## Scope

- Affected module(s): `scripts/dev/run_worktree_shared_venv.sh`, `scripts/dev/check_fast_pysf_runtime.py`, environment/bootstrap/readiness dependency routing.
- Regression: recurring stale installed fast-pysf source/API after the #5665 closure.
- In scope: make the shared readiness route hydrate or validate the current fast-pysf source, preserve the actionable repair message, and add a regression/contract check for the mismatch.
- Out of scope: PR #5922's SNQI publication-preflight implementation and unrelated training behavior.

## Added Value Estimation

- User impact: prevents false gate failures and avoids accepting an environment that cannot collect supported training tests.
- Benchmark impact: restores trustworthy repository readiness evidence; it does not change benchmark semantics.
- Maintenance impact: removes repeated manual environment repair during PR gates.
- Why now: the failure recurred in this batch gate and blocks binary full-readiness classification.

## Effort Estimation

- Rough estimate (hours): 1–3
- Best estimate (hours): 2
- Unknowns: whether the shared-venv wrapper can safely reinstall the editable subtree without affecting concurrent worktrees.

## Complexity Estimation

- Implementation complexity: low to medium; dependency-resolution and worktree-path semantics need explicit handling.
- Dependencies: uv, the checked-out `fast-pysf` subtree, shared-worktree wrapper behavior.
- Open questions: whether to force a local editable install or fail closed before any test collection when the installed module fingerprint is stale.

## Risk Assessment

- Functional risk: low if limited to environment validation and hydration; medium if reinstall routing changes.
- Compatibility risk: a wrapper change could affect users intentionally reusing a different environment.
- Rollout risk: concurrent agents may observe different installed package state.
- Mitigation: compare the imported module path/API fingerprint with the checked-out subtree and keep the repair command explicit and deterministic.

## Affected Files

- `scripts/dev/run_worktree_shared_venv.sh` - shared virtual-environment routing and source freshness checks.
- `scripts/dev/check_fast_pysf_runtime.py` - actionable runtime contract.
- `tests/dev/test_check_fast_pysf_runtime.py` - regression coverage for stale/missing API state.
- `tests/dev/test_base_sensitive_gate_contract.py` - collection/readiness contract if needed.

## Definition of Done

- [ ] A fresh repository-supported environment collects `pytest -m base_sensitive --collect-only --quiet` without the missing-symbol errors.
- [ ] Shared-worktree validation either hydrates the current fast-pysf API or fails before collection with an actionable, deterministic repair path.
- [ ] A focused regression/contract test covers the stale installed-module mismatch.
- [ ] `PR_READY_MODE=final BASE_REF=origin/main scripts/dev/pr_ready_check.sh` reaches a completed core lane without this baseline failure.
- [ ] Existing fast-pysf compatibility tests remain green.

## Success Metrics

- Reproduction is deterministic and no longer recurs after the documented repair path.
- The base-sensitive collection contract returns zero collection errors.
- The repository readiness pipeline can distinguish code failures from environment freshness failures.

## Validation / Testing

- [ ] Reproduce the missing-symbol failure in a controlled stale environment.
- [ ] Verify the focused runtime and base-sensitive collection tests pass after the fix.
- [ ] Run `uv run pytest fast-pysf/tests -v` and the relevant readiness lane.
- [ ] Run the repository validation gate.

## Estimate Discussion

- Why these values were proposed: the failure is localized to deterministic environment/source resolution, but wrapper concurrency and editable-install behavior need verification.
- Uncertainty / confidence: medium confidence (0.8) in the scope; exact repair path depends on the intended shared-venv contract.
- What evidence would move the estimate: a clean bootstrap plus two independent shared-worktree readiness runs.

## Project Metadata

- Priority: high while full-readiness gates are blocked; otherwise normal technical debt.
- Effort (h): 2
- Reviewed: no

## Archetype Metadata

```yaml
archetype: workflow
evidence_tier: blocked
linked_policy:
  - docs/context/issue_713_batch_first_issue_workflow.md
```

## Related Context

- Replaces the currently closed baseline-friction record in #5665 with a fresh recurrence.
- Observed while gating PR #5922; it is not a finding in #5922's changed files.

### PR DESCRIPTION
**Pull request by ll7**
## What / Why

This PR addresses the stale virtual environment imports of `pysocialforce` in linked git worktrees (Issue #5934).
In a linked git worktree reusing the main checkout's `.venv` (where `pysocialforce` is installed as an editable package pointing to the main checkout's path), Python fails to pick up worktree-local changes of `pysocialforce`.

To resolve this:
1. We modified `scripts/dev/run_worktree_shared_venv.sh` to put the worktree root before its `$repo_root/fast-pysf` vendored source in `PYTHONPATH`. This keeps repository modules from being shadowed while still loading the worktree-local `pysocialforce` API.
2. We simplified `scripts/dev/check_fast_pysf_runtime.py` to directly validate the availability of the required `social_force_gil_releasing_context` API from `pysocialforce.forces` and print actionable repair instructions on failure.
3. We updated and added regression/contract tests in `tests/test_ci_script_contract.py` and `tests/dev/test_check_fast_pysf_runtime.py` to cover these changes.

## Validation Output

`uv run pytest tests/dev/test_check_fast_pysf_runtime.py` output:
```
============================= test session starts ==============================
platform linux -- Python 3.13.13, pytest-9.1.1, pluggy-1.6.0
collected 3 items

tests/dev/test_check_fast_pysf_runtime.py ...                            [100%]
============================== 3 passed in 0.05s ===============================
```

`uv run pytest tests/test_ci_script_contract.py -k worktree_shared_venv` output:
```
============================= test session starts ==============================
platform linux -- Python 3.13.13, pytest-9.1.1, pluggy-1.6.0
collected 83 items / 70 deselected / 13 selected

tests/test_ci_script_contract.py .............                           [100%]
====================== 13 passed, 70 deselected in 0.37s =======================
```

`scripts/dev/run_worktree_shared_venv.sh -- pytest -m base_sensitive` output:
```
============================= test session starts ==============================
platform linux -- Python 3.13.13, pytest-9.1.1, pluggy-1.6.0
collected 17346 items / 17325 deselected / 21 selected

tests/benchmark/test_runner_circuit_breaker.py .........                 [ 42%]
tests/benchmark/test_runner_exception_logging.py .                       [ 47%]
tests/benchmark/test_snqi_pareto_pinned_artifact.py ...                  [ 61%]
tests/dev/test_optional_import_pr_freshness.py ..                        [ 71%]
tests/test_gymnasium_env_contracts.py .                                  [ 76%]
tests/test_optional_import_guard_inventory.py .....                       [100%]

==================== 21 passed, 17325 deselected in 20.47s =====================
```

`uv run ruff check` output:
```
All checks passed!
```

This PR was produced by the agy/Gemini-3.5-Flash cheap implementation lane; the review gate hardens and merges.

Closes #5934

## Successor slice / non-duplication

This is the repository-side successor slice for the recurring shared fast-pysf readiness blocker recorded from PR #5922. It owns hydration and preflight validation in `run_worktree_shared_venv.sh`; it does not duplicate PR #5922's publication-preflight implementation or change benchmark behavior.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved the runtime readiness check with clearer “missing vs not callable” messaging and consistent exit code behavior.
  * Updated shared virtual environment execution to ensure imports resolve to the intended vendored source via the correct `PYTHONPATH` ordering.

* **Tests**
  * Refactored runtime-contract tests to use a shared subprocess helper.
  * Added regression coverage for non-callable and import-failure cases, including expected repair guidance.
  * Updated CI contract checks for the strengthened `PYTHONPATH` expectations.

### CODE REVIEW

**Comment by ll7** [comment]
## Gate findings — PR #5945

Reviewed head: `cad9d56afe9c97b0156213a528793209c4785a63` against the linked Issue #5934 and the current diff.

Open review threads: 2.

1. Gemini Code Assist (medium): the checker catches `AttributeError` around the import and can misreport an internal import-time bug as a stale installation; use an ImportError-only import boundary. Verdict: fixed (phase-2 repair).
2. Gemini Code Assist (medium): the shared-venv help text and freshness-check comments still say `pysocialforce` is not shadowed by `PYTHONPATH`, although this diff now prepends `fast-pysf`. Verdict: fixed (phase-2 repair).

Additional gate findings:

3. The new checker only verifies that the symbol can be imported; it no longer preserves the prior callable check, so a present but non-callable symbol can pass the runtime gate. Restore the callable contract and add regression coverage. Verdict: fixed (phase-2 repair).
4. The diff removes the subprocess-level stale-package regression test and replaces it with `sys.modules` injection. That does not prove the executable script behaves correctly in a fresh process or through the shared-worktree route required by Issue #5934. Restore process-level coverage while retaining focused unit coverage. Verdict: fixed (phase-2 repair).
5. The PR contract check reports a successor-slice warning because Issue #5934 has a prior merged reference but this body has no explicit successor/non-duplication statement. Add the required body metadata before acceptance. Verdict: fixed (phase-2 body repair).

CodeRabbit has 0 open review threads; its rate-limit comment is advisory and does not substitute for this gate review.

gate-verdict: changes-requested @ cad9d56afe9c97b0156213a528793209c4785a63

**Comment by ll7** [comment]
Delta gate findings for unchanged post-review head `c018a20165cb9ff84b10ab3bdc4190daa36255de`.

Open review threads: 1. Prior Gemini threads were individually addressed and resolved; CodeRabbit has one newly open thread:

1. CodeRabbit minor — `run_worktree_shared_venv.sh` puts `fast-pysf` before the repository root in `PYTHONPATH`, allowing vendored top-level modules to shadow repository modules. Verdict: fixed in phase 2. The narrow repair will put the repository root first while retaining `fast-pysf` ahead of the virtual-environment package, and update the contract assertions/help text.

The prior gate findings at `cad9d56afe9c97b0156213a528793209c4785a63` stand; #5945 remains changes-requested until this delta is pushed, validated, and all checks are green.

gate-verdict: changes-requested @ c018a20165cb9ff84b10ab3bdc4190daa36255de

**Comment by ll7** [comment]
Delta gate findings for repair head `1e0d793004ef7b508e377e94d9cc4b066020c735`.

Open review threads: 1.

1. CodeRabbit minor — `run_worktree_shared_venv.sh` placed `fast-pysf` before the repository root in `PYTHONPATH`, allowing vendored top-level modules to shadow repository modules. Verdict: fixed. Commit `1e0d7930` puts the repository root first, retains `fast-pysf` ahead of the installed package, and updates the help text and contract assertions.

The two earlier Gemini threads were already resolved with fixed verdicts in the prior gate pass. The PR remains changes-requested until the new-head checks complete and the final open-thread count is rechecked.

gate-verdict: changes-requested @ 1e0d793004ef7b508e377e94d9cc4b066020c735

**Comment by ll7** [comment]
Final gate findings for exact head `24a061b6f9742a497c8abd6ceda9d82268930f91`.

0 open review threads. CodeRabbit’s completed review and the earlier Gemini review threads have no unresolved comments.

Review-bot findings:

1. Gemini — the runtime checker needed to catch only the expected `ImportError` so genuine import bugs are not masked. Verdict: fixed. The checker now preserves callable-symbol validation and reports only the intended import failure path.
2. Gemini — help text/comments and contract expectations described the old `PYTHONPATH` precedence. Verdict: fixed. They now document repository-root-first ordering with `fast-pysf` still ahead of the installed package.
3. CodeRabbit — `fast-pysf` before the repository root could shadow repository top-level modules. Verdict: fixed. Commit `1e0d7930` changes the export and assertions; the refreshed merge head preserves it.

Gate findings:

4. The runtime checker’s callable-symbol contract was restored and covered. Verdict: fixed.
5. Subprocess regression coverage now proves the intended source/package resolution, including non-callable and import-failure cases. Verdict: fixed.
6. Successor metadata was made explicit in the PR body, with no duplicate implementation claim. Verdict: fixed.

Closure: the PR body declares `Closes #5934`, and no deferred scope remains.

Proof: full `pr_ready_check` passed on exact head `24a061b6` against `origin/main=cbf469b7`; the focused runtime/CI-contract suite passed 84 tests, shell syntax and `git diff --check` passed, and all remote checks passed. The PR is non-draft, mergeable, current on main, and the exact-SHA merge hold check allowed it.

gate-verdict: accepted @ 24a061b6f9742a497c8abd6ceda9d82268930f91
