### ISSUE TITLE
friction: shared readiness environment misses fast-pysf GIL-release API

### ISSUE THREAD

**Issue by ll7** [ll7/robot_sf_ll7#5934]
## Goal / Problem

**Observed behavior**

The full `BASE_REF=origin/main scripts/dev/pr_ready_check.sh` gate on PR #5922 stops during collection because the shared virtual environment imports an older installed `pysocialforce` that lacks `pysocialforce.forces.social_force_gil_releasing_context`. The same mismatch causes `pytest -m base_sensitive --collect-only --quiet` to fail with 21 collection errors in training/tool modules.

This repeats the already-closed friction tracked in #5665 after the threaded SocialForce API landed in #5639 / #4981.

**Expected behavior**

A fresh or shared worktree readiness environment should resolve the checked-out `fast-pysf/pysocialforce` API, or fail before collection with a deterministic repair path that the readiness workflow can execute. The base-sensitive selector should collect successfully in a repository-supported environment.

## Reproduction

```bash
BASE_REF=origin/main scripts/dev/pr_ready_check.sh
uv run python -m pytest -m base_sensitive --collect-only --quiet
uv run python scripts/dev/check_fast_pysf_runtime.py
```

Observed 2026-07-17 on gate worktree for PR #5922:

```text
ImportError: cannot import name 'social_force_gil_releasing_context' from 'pysocialforce.forces'
21/17133 tests collected, 21 errors during collection
```

The checkout contains the symbol at `fast-pysf/pysocialforce/forces.py`; the reused environment resolves `/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.12/site-packages/pysocialforce/forces.py` without it.

## Scope

- Affected module(s): `scripts/dev/run_worktree_shared_venv.sh`, `scripts/dev/check_fast_pysf_runtime.py`, environment/bootstrap/readiness dependency routing.
- Regression: recurring stale installed fast-pysf source/API after the #5665 closure.
- In scope: make the shared readiness route hydrate or validate the current fast-pysf source, preserve the actionable repair message, and add a regression/contract check for the mismatch.
- Out of scope: PR #5922's SNQI publication-preflight implementation and unrelated training behavior.

## Added Value Estimation

- User impact: prevents false gate failures and avoids accepting an environment that cannot collect supported training tests.
- Benchmark impact: restores trustworthy repository readiness evidence; it does not change benchmark semantics.
- Maintenance impact: removes repeated manual environment repair during PR gates.
- Why now: the failure recurred in this batch gate and blocks binary full-readiness classification.

## Effort Estimation

- Rough estimate (hours): 1–3
- Best estimate (hours): 2
- Unknowns: whether the shared-venv wrapper can safely reinstall the editable subtree without affecting concurrent worktrees.

## Complexity Estimation

- Implementation complexity: low to medium; dependency-resolution and worktree-path semantics need explicit handling.
- Dependencies: uv, the checked-out `fast-pysf` subtree, shared-worktree wrapper behavior.
- Open questions: whether to force a local editable install or fail closed before any test collection when the installed module fingerprint is stale.

## Risk Assessment

- Functional risk: low if limited to environment validation and hydration; medium if reinstall routing changes.
- Compatibility risk: a wrapper change could affect users intentionally reusing a different environment.
- Rollout risk: concurrent agents may observe different installed package state.
- Mitigation: compare the imported module path/API fingerprint with the checked-out subtree and keep the repair command explicit and deterministic.

## Affected Files

- `scripts/dev/run_worktree_shared_venv.sh` - shared virtual-environment routing and source freshness checks.
- `scripts/dev/check_fast_pysf_runtime.py` - actionable runtime contract.
- `tests/dev/test_check_fast_pysf_runtime.py` - regression coverage for stale/missing API state.
- `tests/dev/test_base_sensitive_gate_contract.py` - collection/readiness contract if needed.

## Definition of Done

- [ ] A fresh repository-supported environment collects `pytest -m base_sensitive --collect-only --quiet` without the missing-symbol errors.
- [ ] Shared-worktree validation either hydrates the current fast-pysf API or fails before collection with an actionable, deterministic repair path.
- [ ] A focused regression/contract test covers the stale installed-module mismatch.
- [ ] `PR_READY_MODE=final BASE_REF=origin/main scripts/dev/pr_ready_check.sh` reaches a completed core lane without this baseline failure.
- [ ] Existing fast-pysf compatibility tests remain green.

## Success Metrics

- Reproduction is deterministic and no longer recurs after the documented repair path.
- The base-sensitive collection contract returns zero collection errors.
- The repository readiness pipeline can distinguish code failures from environment freshness failures.

## Validation / Testing

- [ ] Reproduce the missing-symbol failure in a controlled stale environment.
- [ ] Verify the focused runtime and base-sensitive collection tests pass after the fix.
- [ ] Run `uv run pytest fast-pysf/tests -v` and the relevant readiness lane.
- [ ] Run the repository validation gate.

## Estimate Discussion

- Why these values were proposed: the failure is localized to deterministic environment/source resolution, but wrapper concurrency and editable-install behavior need verification.
- Uncertainty / confidence: medium confidence (0.8) in the scope; exact repair path depends on the intended shared-venv contract.
- What evidence would move the estimate: a clean bootstrap plus two independent shared-worktree readiness runs.

## Project Metadata

- Priority: high while full-readiness gates are blocked; otherwise normal technical debt.
- Effort (h): 2
- Reviewed: no

## Archetype Metadata

```yaml
archetype: workflow
evidence_tier: blocked
linked_policy:
  - docs/context/issue_713_batch_first_issue_workflow.md
```

## Related Context

- Replaces the currently closed baseline-friction record in #5665 with a fresh recurrence.
- Observed while gating PR #5922; it is not a finding in #5922's changed files.

**Comment by ll7** [comment]
Gate propagation: PR #5945 merged at `24a061b6`; shared-worktree fast-pysf hydration/preflight and the root-first import contract are landed; no remaining scope was declared in the PR.
